### ISSUE TITLE
Slight delay before alert appears

### ISSUE THREAD

**Issue by edinabazi** [themeteorchef/bert#11]
Ever since v2 there's a slight delay when you call the alert. It's quite irritating. Could you please fix it?

**Comment by themeteorchef** [comment]
If you ask a little nicer I'd be glad to take a look :)

**Comment by edinabazi** [comment]
I actually reread my post before I submitted it and I thought it wasn't very nice, but I didn't think you'd mind. I sincerely apologize. I seriously appreciate all of your work and can't be thankful enough, and I surely didn't mean to sound impolite.

**Comment by themeteorchef** [comment]
@edinchez updated. Reduced the timeouts and tweaked how alerts are set. Should be a little speedier now.

**Comment by jahosh** [comment]
@themeteorchef is it possible to manipulate the timeout from the api? I'd like to make the alerts a bit faster as well.

**Comment by themeteorchef** [comment]
@Jahosh only on a global basis at the moment (not per alert). You can set the defaults from anywhere on the client using `Bert.defaults = { hideDelay: 3500 }`, adjusting `3500` to whatever delay you're after (in milliseconds).
