### ISSUE TITLE
Had to manually add {{> bertAlert}} template

### ISSUE THREAD

**Issue by EliotSlevin** [themeteorchef/bert#12]
Installed the package, alerts wouldn't show up. The Bert object was in the terminal, but any methods were undefined. On a hunch put the {{> bertAlert}} template in myself, worked fine then. 

No idea what was stopping the tag getting auto added, but here's all the packages that were in the project.

```
insecure
useraccounts:semantic-ui
iron:router
useraccounts:core
accounts-password
rubaxa:sortable

underscore
semantic:ui-css
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
houston:admin
meteorhacks:kadira
themeteorchef:bert
```

**Comment by themeteorchef** [comment]
Hey Eliot, which version of Bert are you using?

**Comment by EliotSlevin** [comment]
Oh whoops my bad, it's at 1.1.0. I installed it after reading your update article, I just presumed it would be 2.0. I guess 2.0 hadn't quite got onto atmosphere yet.

**Comment by themeteorchef** [comment]
@EliotSlevin Gotcha :) Should it be made clearer in the article?
