### ISSUE TITLE
Doesn't work with Stylus

### ISSUE THREAD

**Issue by GilbertMizrahi** [themeteorchef/bert#17]
It will be nice if it could work with Stylus as well.

**Comment by themeteorchef** [comment]
Can you explain what isn't working? The CSS is written with Sass but Stylus should be able to override the CSS just fine in your app.

**Comment by GilbertMizrahi** [comment]
I am sorry I didn't answer before. As it turned out the problem was a bug on my app and not a problem with Bert, but my app worked fine with sAlert at that time, so I thought the problem was with Bert. My apologies.
