### ISSUE TITLE
Testing isn't seeing local package

### ISSUE THREAD

**Issue by chancesmith** [themeteorchef/bert#24]
themeteorchef:bert@1.1.0 is installed. We're having issues getting Bert to work in project.

We're using the following inside of an event after successful insert into mongo collection...

```
Bert.alert({
      title: 'Post Added',
      message: 'It worked!',
      type: 'success',
      style: 'growl-top-right'
});
```

This is what we get when we try to see tests of Bert package.

```
$ meteor test-packages themeteorchef:bert --port 3001
=> Errors while collecting tests:

While trying to test package `themeteorchef:bert`:
error: Not a known local package, cannot test
```

We might have a package conflict. Run into any similar results?

**Comment by themeteorchef** [comment]
Hey @chancesmith :) Haven't run into this error before, but I would check and make sure that you're storing Bert in your local packages directory [specified via the `PACKAGE_DIRS` variable](https://themeteorchef.com/recipes/writing-a-package/#tmc-local-packages).

If you place your copy of Bert in the directory set to that URL, Meteor should quit barking and run the tests as expected.
