### ISSUE TITLE
How to use it in Meteor 1.3

### ISSUE THREAD

**Issue by deepupathak** [themeteorchef/bert#27]
Hello !
Please tell me about how to use it in meteor 1.3 with React ?

**Comment by themeteorchef** [comment]
You can just call the `Bert.alert()` command from anywhere. It does currently have a dependency on Blaze but works just fine. Here's [an example file](https://github.com/themeteorchef/base/blob/8d9feb929b0b975d9c6c43170ad526f60934f76f/imports/ui/components/document.js#L32) from [Base](https://github.com/themeteorchef/base).

**Comment by deepupathak** [comment]
Thanks for your help. Its working now.
now lets close all this.
