### ISSUE TITLE
Multi Alert Doesn't work

### ISSUE THREAD

**Issue by Infinitism** [themeteorchef/bert#42]
Hi, 

When I was trying to use Bert to display several error messages at once called inside a foreach of an array of error messages and only the last array item seems to be created and messages don't seem to stack on top of eachother.

**Comment by themeteorchef** [comment]
Hi @Infinitism, at the moment Bert doesn't support stacking. The new messages just swap out. Flagging this as a possible feature but going to close it out as it's not a bug with the current API.
