### ISSUE TITLE
Error when setting Bert.defaults

### ISSUE THREAD

**Issue by manuelmateus16** [themeteorchef/bert#5]
Hello!

First of all thanks for this nice and helpful package, along with all the tutorials on meteor chef :)

Now, related to the specific issue I am facing:

When I don't set any Bert.defaults and call (as example)

```
Bert.alert("My error", "danger") 
```

I get my expected error coming in the default type, fixed-top.

Now, I have set all the alerts in my application only specifing the error and the type, not specifying the style (is this required?).

I wanted to change the default style to growl-top-right, but when I do it with

```
Bert = {
  defaults: {
    style: "growl-top-right",
   }
}
```

In the client, when an alert should display, I get 

```
"Uncaught TypeError: undefined is not a function"
```

in my code: 

```
Bert.alert("My error", "danger") 
```

Is this an issue? 

Thanks

**Comment by themeteorchef** [comment]
Hmm I don't think it's an issue but maybe an improvement to the README. If you take a look at the defaults section, there's a note about setting defaults beneath the list of available settings:

> To set a new default, just call Bert.defaults.<setting> in your client code. For example, to disable Bert's autoHide functionality, you would set Bert.defaults.autoHide = false;.

Could you try setting it this way and let me know if you're still getting an error? Also let me know if the current docs are confusing so I can make an update :)

**Comment by manuelmateus16** [comment]
Oh you are right, I thought i could just set the defaults by setting a new Bert = {...}. Now it's working as I wanted. Maybe if there was a way to override the whole Bert defaults object with a new Bert object would be nice.

**Comment by themeteorchef** [comment]
You should be able to do this now, e.g. you could set:

```
Bert.defaults = {
  animated: true,
  animationSpeed: 300,
  autoHide: true,
  dismissable: true,
  hideDelay: 3500,
  style: "fixed-top",
  type: "default"
}
```

Keep in mind if you implement it this way, though, all of the properties will need a setting. I'll keep this in mind, though, for the next version as there are a few ways to improve it :)

**Comment by MonalisaGit** [comment]
Hello,
I am using this ackage in meteor.when i m doing two different operation  like delete and add that while i m doing delete its overriding my add alert message.what i need to do for getting my delete alert msg.help me to avoide override it.

**Comment by cleverbeagle** [comment]
Hi @MonalisaGit. Messages cannot be deleted. Once they're displayed, the only way to remove them is to call `Bert.alert()` again or wait for the number of seconds assigned to `Bert.defaults.hideDelay` to pass.
