### ISSUE TITLE
Support new Font-Awesome icons

### ISSUE THREAD

**Issue by sgup** [themeteorchef/bert#53]
I'm using the latest font-awesome version, which uses a `fas-` `far-` syntax. Out-of-the box, adding this package doesn't work with the new icons.

**Comment by cleverbeagle** [comment]
Hi @sgup if you pass the full new class name does it work? E.g. `icon: 'fas fas-<icon>'`

**Comment by sgup** [comment]
not really. That would still prepend `fa ` into the icon class. They've split it up into brands, solid, regular, which are free, and more paid styles. the `fa` class definition still seems to be there, and causes icons to not render correctly.

See my updates here: https://github.com/sgup/bert-fontawesome5/commit/781a12f8bb563545b8598f056c71a4f66310f343

I've also updated some icon names, they renamed them.

**Comment by cleverbeagle** [comment]
@sgup ahh okay, bummer, got it. Thanks for sharing that PR. I've been wanting to give Bert some attention for awhile but it's been low priority. I'll reference this when I loop back around.

**Comment by Twisterking** [comment]
Any updates on this? I would like to update newest font-awesome as well but Bert is holding me back! 😢

**Comment by cleverbeagle** [comment]
Hey @Twisterking, just put something on my list to upgrade FA over the holiday. I'll follow up here once it's live.

**Comment by sgup** [comment]
@Twisterking if you're using react, check out [`react-toastify`](https://github.com/fkhadra/react-toastify)! I ended up switching since it was more flexible.

**Comment by cleverbeagle** [comment]
@Twisterking this has been updated (`meteor add themeteorchef:bert@2.2.0`). Unfortunately, the Atmosphere package that Bert depended on for FontAwesome hasn't been updated. The solution was to remove this dependency altogether.

Moving forward, you will need to provide FontAwesome separately, but shouldn't have any conflicts with Bert. [Instructions for adding FontAwesome are here](https://fontawesome.com/start).

**Comment by willydwi77** [comment]
> @Twisterking this has been updated (`meteor add themeteorchef:bert@2.2.0`). Unfortunately, the Atmosphere package that Bert depended on for FontAwesome hasn't been updated. The solution was to remove this dependency altogether.
> 
> Moving forward, you will need to provide FontAwesome separately, but shouldn't have any conflicts with Bert. [Instructions for adding FontAwesome are here](https://fontawesome.com/start).

How to add fontawesome into Bert.alert? I already install 
`npm install --save-dev @fortawesome/fontawesome-free`
and put css and js in the <head>, and I use 
`<i class="fas fa-igloo"></i>` in the **icon:**
icon doesn't show.

I install react-fontawesome too, but it still

**Comment by cleverbeagle** [comment]
@willydwi77 see the link in that comment here: https://fontawesome.com/start. It's best to use the CDN link.
