### ISSUE TITLE
Bert alert does not take correct icon as per the type provided

### ISSUE THREAD

**Issue by iiaishwarya** [themeteorchef/bert#63]
I am using Bert in a project
`Bert.alert("custom message", "success")`

The alert shows the same icon as captured by the first call to Bert. The problem is solved if I refresh the page. Otherwise it is the same icon for the subsequent Bert calls

![image](https://user-images.githubusercontent.com/40992815/85398251-917cdd00-b572-11ea-8fd4-03d916f1172e.png)

**Comment by sourcerer52** [comment]
at https://github.com/themeteorchef/bert/blob/master/bert.js#L76
` $( '.bert-icon').remove(); `
is used

However, icon div has a different class
```
<div class="bert-gem">
        {{{a.icon}}}
 </div>
```

**Comment by iiaishwarya** [comment]
Upgrading the package to V 2.2.2 worked for me.  :)
