### ISSUE TITLE
Configurable template

### ISSUE THREAD

**Issue by genaropicazo** [themeteorchef/bert#8]
Any chance you could make the template name configurable so that the <code>bertAlert</code> template can be overriden. In my case, I want to be able to allow the message to be HTML markup (need to have a link), meaning the template would need to change the line:

<code>&lt;p&gt;{{alert.message}}&lt;/p&gt;</code>

to

<code>&lt;p&gt;{{{alert.message}}}&lt;/p&gt;</code>

That change is pretty simple, but I imagine others could have other requirements as well.

**Comment by themeteorchef** [comment]
Definitely, this makes a lot of sense (something I've thought about myself). 

Are you just looking for the example above (escaping HTML with triple mustache), or the ability to totally override a template. I haven't seen the former, but if you could show me an example I can try to whip it up :)

Let me know and I'll create an issue for this.

**Comment by jshimko** [comment]
@genaropicazo, have you seen the [template-extension](https://atmospherejs.com/aldeed/template-extension) package?  You can override templates while preserving their helpers/events (as well as a bunch of other cool stuff).

Once you've added the package, overriding any template is super simple.  Just create your new template: 

``` html
<template name="myNewTemplate">
   Awesome stuff goes here!
</template>
```

and then:

``` javascript
Template.myNewTemplate.replaces("theOldOne");
```

That's it!

**Comment by themeteorchef** [comment]
@jshimko this awesome! Had no idea this existed. @genaropicazo, does this do the trick for you?

**Comment by genaropicazo** [comment]
@themeteorchef Thank you for the prompt response. At the moment my needs are just for triple mustache, but I thought it would be nice to make the template configurable.

@jshimko I am familiar with the template extension package and is currently what I am using to override the bertAlert template. I just thought it might be more elegant to provide that ability out of the box via configuration.

Thank you both for your responses. I haven't found the need to override templates from other packages yet, but if/when I do, I suppose I can't expect that every package developer will be as responsive as the Meteor Chef, so it may be a good idea to stick with using the template extension package.

**Comment by themeteorchef** [comment]
@genaropicazo all set! Update to v1.1.0 to get some triple mustache action :)
